### ISSUE TITLE
Getting access to the checkpoint

### ISSUE THREAD

**Issue by monatis** [SkunkworksAI/BakLLaVA#3]
Hi, congrats on the release. 

Last week I implemented support for LLaVA v1.5 in llama.cpp, and I'd like to do the same for BakLLaVA. I scanned the fork but couldn't notice any architectural change in the mm projector although the readme mentions about "significant architecture changes." And the HF repo is guarded --I requested access but couldn't get it yet. When will it be public so that I can work for implementing it?

**Comment by pharaouk** [comment]
New code coming soon. V1 is mostly similar arch-wise except a few mods in vision tower which can be turned on/off

**Comment by monatis** [comment]
Thanks. This is now working: https://huggingface.co/mys/ggml_bakllava-1
